/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as appRouteRouteImport } from './../routes/(app)/route'
import { Route as appIndexRouteImport } from './../routes/(app)/index'
import { Route as appMembersRouteImport } from './../routes/(app)/members'
import { Route as appPostsRouteImport } from './../routes/(app)/posts'
import { Route as appSettingsRouteImport } from './../routes/(app)/settings'
import { Route as appTodosRouteImport } from './../routes/(app)/todos'
import { Route as authLoginRouteImport } from './../routes/(auth)/login'
import { Route as authSignupRouteImport } from './../routes/(auth)/signup'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const appMembersRoute = appMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => appRouteRoute,
} as any)
const appPostsRoute = appPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appTodosRoute = appTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => appRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/(auth)/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/members': typeof appMembersRoute
  '/posts': typeof appPostsRoute
  '/settings': typeof appSettingsRoute
  '/todos': typeof appTodosRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesByTo {
  '/members': typeof appMembersRoute
  '/posts': typeof appPostsRoute
  '/settings': typeof appSettingsRoute
  '/todos': typeof appTodosRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/members': typeof appMembersRoute
  '/(app)/posts': typeof appPostsRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/todos': typeof appTodosRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(app)/': typeof appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/members' | '/posts' | '/settings' | '/todos' | '/login' | '/signup' | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/members' | '/posts' | '/settings' | '/todos' | '/login' | '/signup' | '/'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/members'
    | '/(app)/posts'
    | '/(app)/settings'
    | '/(app)/todos'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/members': {
      id: '/(app)/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof appMembersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/posts': {
      id: '/(app)/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof appPostsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/todos': {
      id: '/(app)/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof appTodosRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appRouteRouteChildren {
  appMembersRoute: typeof appMembersRoute
  appPostsRoute: typeof appPostsRoute
  appSettingsRoute: typeof appSettingsRoute
  appTodosRoute: typeof appTodosRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appMembersRoute: appMembersRoute,
  appPostsRoute: appPostsRoute,
  appSettingsRoute: appSettingsRoute,
  appTodosRoute: appTodosRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
